import type User from "./User";

/**
 * TODO
 */
type Sponsor = {
  ...$Shape<User>,
  id: string,
  item_type: string,
  marker: number,
  time_created: string,
  name: string,
  gender: string,
  birthday: string,
  email: string,
  location: string,
  username: string,
  federatedID: string,
  stripeID: string,
  profileImagePath: string,
  profileImagePaths: [string],
  scheduledWorkouts: [string],
  completedWorkouts: [string],
  scheduledTimes: [string],
  reviewsBy: [string],
  reviewsAbout: [string],
  friendlinessRating: string,
  effectivenessRating: string,
  reliabilityRating: string,
  bio: string,
  access: string,
  friends: [string],
  friendRequests: [string],
  challenges: [string],
  completedChallenges: [string],
  ownedChallenges: [string],
  invitedChallenges: [string],
  challengesWon: [string],
  scheduledEvents: [string],
  completedEvents: [string],
  ownedEvents: [string],
  invitedEvents: [string],
  sentInvites: [string],
  receivedInvites: [string],
  posts: [string],
  submissions: [string],
  liked: [string],
  comments: [string],
  groups: [string],
  ownedGroups: [string],
  invitedGroups: [string],
  messageBoards: [string],
  streaks: [string],
  credit: number,
  deals: [string],
}

export default Sponsor;